### ISSUE TITLE
Roadmap para 2.0

### ISSUE THREAD

**Issue by douglasralmeida** [douglasralmeida/prisma#1]
Lista de Recursos a serem desenvolvidos para a versão 2.0:

- [ ] Modo depuração para geração de logs.
- [ ] Instalação/desinstalação de temas.
- [ ] Migrar loader para FreePascal.
- [ ] Melhorar o sistema de ajuda.
